name: food_del
description: "A food delivery app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  collection: ^1.18.0
  flutter_credit_card: ^4.0.1
  intl: ^0.19.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/burgers/
    - lib/images/salads/
    - lib/images/sides/
    - lib/images/desserts/
    - lib/images/drinks/
